### ISSUE TITLE
syn_burst_val download error

### ISSUE THREAD

**Issue by HyoungwonCho** [placerkyo/BSRD#1]
Hello!

I am unable to download the file from the syn_burst_val link in the Evaluation section of the Readme. Could you please let me know if there is another way to access it?

**Comment by placerkyo** [comment]
Please download from https://github.com/goutamgmb/deep-burst-sr or https://drive.google.com/file/d/1DHu3-_tGSc_8Wwwu6sHFaPtmd9ymd0rZ/view.

**Comment by HyoungwonCho** [comment]
Thank you very much for your excellent research and prompt response. :)

**Comment by HyoungwonCho** [comment]
I have one more question. The download of the "PWC Trained model" for the BurstSR dataset Evaluation is also not working correctly. Is there a solution for this?

Thank you.

**Comment by placerkyo** [comment]
The issue is that these links from https://github.com/goutamgmb/NTIRE21_BURSTSR are no longer valid. It might be quickest to ask them directly. Alternatively, you might find the PWCNet weights at https://github.com/sniklaus/pytorch-pwc or by checking other Burst SR methods on GitHub (such as https://github.com/goutamgmb/deep-burst-sr or https://github.com/akshaydudhane16/Burstormer).

**Comment by HyoungwonCho** [comment]
Aha, I see. I will try the methods you suggested. Thank you for your detailed response!
